### ISSUE TITLE
Lights Off - Minor Suggestions

### ISSUE THREAD

**Issue by ShockValu3** [david-c14/ModularFungi#12]
Feature Request - CV Control

Feature Request - Dim up/down control with middle mouse scroll wheel (windows)

UI Request - Rename "Dim" to "Brightness" or similar so Up is brighter and Down is Dimmer.  Right now it's the opposite and a bit awkward.

**Comment by david-c14** [comment]
@stoermelder Do you want to consider / respond to these suggestions.

I think direct CV control is unlikely, but it could be made compatible with SAIL.

**Comment by stoermelder** [comment]
> Feature Request - CV Control
> 
> Feature Request - Dim up/down control with middle mouse scroll wheel (windows)
> 
> UI Request - Rename "Dim" to "Brightness" or similar so Up is brighter and Down is Dimmer. Right now it's the opposite and a bit awkward.

Thank you for your feature requests, I will talk to Omri how he thinks about them.

About the label „Dim“: I think about it the other way around, on 100% the module dims the light by 100% to full dark, on 0% the module dims the light by 0% with no effect at all.

**Comment by david-c14** [comment]
If we added an invisible vertical slider to the main panel.  The user could sweep their mouse up and down the panel to change the Dim value.  

This would not change the aesthetic, but would give an extra degree of control, and SAIL could recognise the parameter for automation.

**Comment by stoermelder** [comment]
I was thinking the same direction. It would not even need a real slider, it would be enough to add an invisible ParamWidget which can be mapped and reacts on scroll events.

**Comment by david-c14** [comment]
That would work.  I just thought that a slider would already have the event handlers.

**Comment by david-c14** [comment]
Available in version 1.1.1
