### ISSUE TITLE
Lights Off doesn't seem to be doing anything on Mac OS X

### ISSUE THREAD

**Issue by pgatt** [david-c14/ModularFungi#13]
Hi there, Lights off doesn't seem to be working here. Mac OS X 10.14.6, Rack 1.1.6. Tried using the shortcut  and manually changing the dimness, to no avail.

**Comment by nay-seven** [comment]
For info, same config here (Mac OS X 10.14.6, Rack 1.1.6.) and it works, but i need to use CTRL+Alt+X, not CMD+Alt+X  ;-)

**Comment by pgatt** [comment]
@nay-seven can now confirm that. I thought I had tried most combinations. Ctrl Alt X works.

**Comment by nay-seven** [comment]
good news

**Comment by david-c14** [comment]
@stoermelder

**Comment by david-c14** [comment]
The key matching should probably be done against RACK_MOD_CTRL rather than GLFW_MOD_CONTROL

The text on the menu item can also use a macro so that it can be OS specific  RACK_MOD_CTRL_NAME

**Comment by stoermelder** [comment]
> @nay-seven can now confirm that. I thought I had tried most combinations. Ctrl Alt X works.

Ok thanks, I will correct the label in the context menu.

**Comment by MackenMations** [comment]
Hi, I'm also running Rack 1.1.6 on Mac OS X 10.14.6, but for some reason neither CTRL nor CMD +ALT+X work for me. Can't seem to figure it out...?

**Comment by MackenMations** [comment]
Any suggestions?

**Comment by stoermelder** [comment]
Which language layout does your keyboad have?

**Comment by MackenMations** [comment]
It's a Finnish Keyboard, and most of the time I use that layout, but changing to the British layout doesn't do anything.

**Comment by stoermelder** [comment]
Can anyone confirm that the fix I applied enables the module to work on Mac OS? I can't verify because I had no problems with the hotkey in the first place (except for the Cmd/Alt confusion). You need to build the plugin from the dev branch for testing.

**Comment by stoermelder** [comment]
I'm closing this issue. If anyone has further problems please comment or open a new issue.

**Comment by MackenMations** [comment]
Hi,
Yes, this now works on Mac OS X.
Many thanks.
