### ISSUE TITLE
Lights off working in windows 10

### ISSUE THREAD

**Issue by ghost** [david-c14/ModularFungi#14]
HI ok I got it working.  For some reason the control to turn in on and off is sensitive.  

Also can you add overhead lighting effects as a separate module to create color accents over the rig?  See State Azure example.  

Also see Sworn64 lighting effects.  It would be cool in VCV. Strobes and so forth

**Comment by stoermelder** [comment]
> HI ok I got it working. For some reason the control to turn in on and off is sensitive.

Thank you for this info, it is no more sensitive than every other hotkey command in Rack.

On your other requests: These things are unlikely to happen.
