### ISSUE TITLE
Lights Off hides translucent lit widgets, as implemented in Darius or Infix

### ISSUE THREAD

**Issue by AriaSalvatrice** [david-c14/ModularFungi#15]
![image](https://user-images.githubusercontent.com/25130242/84325463-12070b00-ab7b-11ea-9a3d-588111eb6712.png)

![image](https://user-images.githubusercontent.com/25130242/84325517-395dd800-ab7b-11ea-8c6f-3953400973c3.png)

Tested on Windows 10. To reproduce, just add Darius or Infix to the rack. Those widgets are made with semi-transparent SVG overlaid over a light the same size.

Relevant bits from Darius: 
https://github.com/AriaSalvatrice/AriaVCVModules/blob/d70f0094a3c2b565ebcf0c5b0c0ee66948cf8bb1/src/AriaComponents.hpp#L70
https://github.com/AriaSalvatrice/AriaVCVModules/blob/d70f0094a3c2b565ebcf0c5b0c0ee66948cf8bb1/src/Darius.cpp#L411

**Comment by stoermelder** [comment]
Yes, you are right. I need to think about a solution for this issue.

**Comment by AriaSalvatrice** [comment]
People have detailed techniques to make lights off compatible widgets in this thread 

https://community.vcvrack.com/t/how-much-do-you-care-about-the-visual-design-of-rack-modules/10460/31

**Comment by david-c14** [comment]
Yes. They have done it by changing their modules to be compatible with Lights Off.  Rather than the other way round.

I don't think it would be a simple change for Darius, I think you would have to create custom widgets which descended from both PortWidget and LightWidget, and then override the draw method.  Although you might be able to just call both of the base class Draw methods one after the other.

**Comment by AriaSalvatrice** [comment]
Another forum thread here now: https://community.vcvrack.com/t/modules-that-work-with-modular-fungi-lightsoff/10477

**Comment by stoermelder** [comment]
@AriaSalvatrice I fixed it in my modules by "cutting out" the area covered by port from the light. This might not be doable in every case but it did it for my modules.
https://github.com/stoermelder/vcvrack-packone/blob/b82f19df8e7ce267a5ef4694db0f2ac06fa6ccdb/src/components.hpp#L279

**Comment by david-c14** [comment]
Development for Modular Fungi is currently on hold.

Lights off functionality is now managed within VCVRack v2.  So changes to the v1 of Modular Fungi is now unlikely.
