### ISSUE TITLE
Builds

### ISSUE THREAD

**Issue by david-c14** [david-c14/ModularFungi#2]
Windows:
[ModularFungi-0.6.0-win.zip](https://github.com/david-c14/ModularFungi/files/2218350/ModularFungi-0.6.0-win.zip)

Linux:
[ModularFungi-0.6.0-lin.zip](https://github.com/david-c14/ModularFungi/files/2237791/ModularFungi-0.6.0-lin.zip)

**Comment by squinkylabs** [comment]
You might use the "releases" feature of GitHub to make these more findable. Of course if they are going in the plugin manager it will be moot.

**Comment by david-c14** [comment]
Good plan.

**Comment by ghost** [comment]
Mac:
[ModularFungi-0.6.0-mac.zip](https://github.com/david-c14/ModularFungi/files/2238308/ModularFungi-0.6.0-mac.zip)

**Comment by david-c14** [comment]
Thank you
