### ISSUE TITLE
Lightsoff Plugin crashes in VCV for Linux

### ISSUE THREAD

**Issue by lepidopteralady1781** [david-c14/ModularFungi#22]
Below you will see attached a gif of what happens, a picture of my system information, and the contents of my log.txt file.

![fungi_vcv_crash](https://user-images.githubusercontent.com/26756285/87389290-181e4c00-c56c-11ea-9c34-fef3b398bf63.gif)
![vcv rack help](https://user-images.githubusercontent.com/26756285/87389291-1a80a600-c56c-11ea-9404-de1c9d60a4cc.png)
[log.txt](https://github.com/david-c14/ModularFungi/files/4916806/log.txt)

**Comment by curlymorphic** [comment]
I have just done some tests, and it appears the DBUG module causes rack to crash when placed on the right-hand side of any module I tested with.

I have reported this bug upstream
https://github.com/captainssounds/vcv-CaptainsSounds/issues/35

**Comment by david-c14** [comment]
Sounds like the problem lies elsewhere
