### ISSUE TITLE
The Opsylloscope popup window isn't resizeable after you've launched a VCV-Host VST editor window

### ISSUE THREAD

**Issue by RichieHindle** [david-c14/ModularFungi#31]
The Opsylloscope popup window is normally resizeable, but after you've launched a VCV-Host VST editor window, it isn't.

In the code section "Tell GLFW the properties of the window we want to create" you need to call this:

`glfwWindowHint(GLFW_RESIZABLE, GLFW_TRUE);`

Otherwise, GLFW will default the GLFW_RESIZABLE property to be the same as the last window created, and if that's a VST editor window, it won't be resizable.

**Comment by curlymorphic** [comment]
@RichieHindle Thanks for both the report and the solution.

@david-c14 I shall make the changes now, and include in the next release. I have additional feature requests to implement.

**Comment by RichieHindle** [comment]
No problem!  (I shouldn't have given Omri buggy code in the first place. 😃 )

**Comment by david-c14** [comment]
Development for Modular Fungi is currently on hold.
