### ISSUE TITLE
Opsilloscope load wav

### ISSUE THREAD

**Issue by Eurikon** [david-c14/ModularFungi#37]
Would be nice if the Scope could load OSciStudio wav file(s), with start trigger :)

**Comment by curlymorphic** [comment]
@Eurikon before I pass this to Omri for consideration can you please provide more details of the expected behaviour.

**Comment by Eurikon** [comment]
Hi, sure.
A basic built-in stereo wav player, that is internally connected to the X & Y
Preferably with wave start, trigger input. 

It will play wav files that generate shapes on the scope.

**Comment by david-c14** [comment]
For my 2 cents, I don't see the use case here. Surely there are already modules that play wav files. You could connect it to the scope with patch cables. 

It's the essence of modular after all.

**Comment by Eurikon** [comment]
Alright, nevermind then 👍🏼

**Comment by curlymorphic** [comment]
I also agree, the modular paradigm of VCV should be used, Thanks for the suggestion, but I shall close this issue.
