### ISSUE TITLE
No ability to change hotkey for Lights Off

### ISSUE THREAD

**Issue by OracleToes** [david-c14/ModularFungi#39]
The hotkey to trigger Lights Off (ctrl + alt + x) is an OS level command on my distribution, I couldn't find a way to change the hotkey for Lights Off without editing the source and compiling myself.

**Comment by david-c14** [comment]
Development for Modular Fungi is currently on hold.

Lights off functionality is now managed within VCVRack v2.  So changes to the v1 of Modular Fungi is now unlikely.
