### ISSUE TITLE
Miss the scope so much — no equal replacement in 2.x

### ISSUE THREAD

**Issue by zmichels** [david-c14/ModularFungi#42]
I’m just writing to say I hope someday you do port these for 2.x. This scope’s ability to display poly signals with a large display and effects is unique and so far not replicated in VCV rack 2.x by any other modules. The closest I can get for similar functionality is a 3-shape XY scope (works with 6 mono inputs)… but I’m needing 4-shapes for my oscillographics goals. The VCV scope will display them, but has a small display and no FX features. Your scope is so rad and does everything I want… but it’s awkward trying to install and use older versions of rack. Anywhooo… thank you for making it… and please  know there are folks like me who love it and wish to continue using your modules with newer versions of Rack.

**Comment by curlymorphic** [comment]
Zmichels

Many thanks for your kind words of encouragement. At Omri's request, a rack 2.x version of this scope has not been published. I shall pass on your message.
