### ISSUE TITLE
Request: Add user definable sets to Modular Fungi

### ISSUE THREAD

**Issue by Shadowhenge** [david-c14/ModularFungi#5]
Your module is great.  Thank you.  I have a suggestion to increase functionality.  

Adding the following lines to the Blanks.cpp (between lines 73 and 74) Should add 2 rows for user definable art if my logic is sound.  I'm not a great programmer by any means.

fileName[2] = FileName("res/User1_%dHP.png", x);
fileName[3] = FileName("res/User2_%dHP.png", x);

Alternately you can move those definitions to a user editable list of plate sets so people can make their own sets, share them, etc.

If the files are absent VCV does not error, it simply produces a black dropshadow that is movable like a blank (cool in its own right)  If you include a set of blank plates labeled as "UserTemplate_3HP.png" which I can throw together for you if you like.  Users can edit them and make thier own sets that won't be overwritten when the module updates. (I tested it with my own and assuming the code to add the categories works, downloading the mod does not overwrite files in the folder that are not normally part of the mod. (delete)

I Think this would be a great feature for the mod and would be happy to make an instructional video for editing and using the extra user templates.

Regards,

Jamie

**Comment by david-c14** [comment]
We thought about this.

But decided no. 

It's taken me far too long to respond, for which I apologise.
