### ISSUE TITLE
Rack v1: plugin.json issues

### ISSUE THREAD

**Issue by cschol** [david-c14/ModularFungi#6]
The manifest validation script has shown the following issues:

```
Validating ModularFungi
Missing key: manualUrl
Blank 1HP: invalid slug
Blank 3HP: invalid slug
Blank 4HP: invalid slug
Blank 6HP: invalid slug
Blank 10HP: invalid slug
Blank 12HP: invalid slug
Blank 16HP: invalid slug
Blank 20HP: invalid slug
Blank 26HP: invalid slug
Blank 32HP: invalid slug
Invalid license ID: BSD-3
```

- Set `manualUrl` to the README.md on GitHub
- Slugs need to adhere to the Rack slug convention. The issue here is the whitespace character.
- The license ID needs to be a valid SPDX license ID as defined on: https://spdx.org/licenses/

**Comment by AndrewBelt** [comment]
Note: you can preserve patch compatibility by simply removing invalid characters, i.e. " ".

**Comment by cschol** [comment]
Sorry, forgot to mention that.

**Comment by david-c14** [comment]
I think these issues are now fixed.

Commit:

https://github.com/david-c14/ModularFungi/commit/cc0c5563389a1ce26d986d6419906600dfc06034

Thank you

**Comment by cschol** [comment]
Thank you. Looks good.
